// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaJh-c4kGtsdHr_8kzF5VO-tJQqG2YPeg',
    appId: '1:633270936961:web:3443dd69dec2b1e878f480',
    messagingSenderId: '633270936961',
    projectId: 'sdcp-b8d5f',
    authDomain: 'sdcp-b8d5f.firebaseapp.com',
    storageBucket: 'sdcp-b8d5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KD_jxuC5kLZt7iyLgoP5Uyf7_L7Ttqk',
    appId: '1:633270936961:android:0bedaf72712fb9a578f480',
    messagingSenderId: '633270936961',
    projectId: 'sdcp-b8d5f',
    storageBucket: 'sdcp-b8d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2RZ2Q3M8XvnSxNSIJEJ8y2hsU0AhHN0w',
    appId: '1:633270936961:ios:031191b2f22cca7778f480',
    messagingSenderId: '633270936961',
    projectId: 'sdcp-b8d5f',
    storageBucket: 'sdcp-b8d5f.firebasestorage.app',
    iosBundleId: 'com.example.sdcpRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2RZ2Q3M8XvnSxNSIJEJ8y2hsU0AhHN0w',
    appId: '1:633270936961:ios:031191b2f22cca7778f480',
    messagingSenderId: '633270936961',
    projectId: 'sdcp-b8d5f',
    storageBucket: 'sdcp-b8d5f.firebasestorage.app',
    iosBundleId: 'com.example.sdcpRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaJh-c4kGtsdHr_8kzF5VO-tJQqG2YPeg',
    appId: '1:633270936961:web:c86a28ba058cdcce78f480',
    messagingSenderId: '633270936961',
    projectId: 'sdcp-b8d5f',
    authDomain: 'sdcp-b8d5f.firebaseapp.com',
    storageBucket: 'sdcp-b8d5f.firebasestorage.app',
  );
}
